syntax = "proto3";

package msg;

enum StatusCode {
  SUCCESS = 0;
  FAILURE = 1;
  INVALID_REQUEST = 2;
  SERVER_ERROR = 3;
}

message Status {
  StatusCode code = 1;
  string message = 2;
}

// CmdID: 1
message HeartbeatMsg {
  string id = 1;
  int64 timestamp = 2;
}

// CmdID: 2
message RandomNumberRequest {
  string id = 1;
  int32 min = 2;
  int32 max = 3;
  int32 interval = 4;
}

// CmdID: 3
message StopRandomNumberRequest {
  string id = 1;
}

// CmdID: 4
message IncrementalSequenceRequest {
  string id = 1;
  int32 start = 2;
  int32 end = 3;
  int32 interval = 4;
}

// CmdID: 5
message StopIncrementalSequenceRequest {
  string id = 1;
}

// CmdID: 6
message EchoRequest {
  string message = 1;
}

// CmdID: 7
message RandomNumberResponse {
  string id = 1;
  Status status = 2;
  int32 number = 3;
}

// CmdID: 8
message StopRandomNumberResponse {
  string id = 1;
  Status status = 2;
}

// CmdID: 9
message IncrementalSequenceResponse {
  string id = 1;
  Status status = 2;
  int32 number = 3;
}

// CmdID: 10
message StopIncrementalSequenceResponse {
  string id = 1;
  Status status = 2;
}

// CmdID: 11
message EchoResponse {
  Status status = 1;
  string message = 2;
}

service MiscService {
  rpc Heartbeat(HeartbeatMsg) returns (HeartbeatMsg);

  rpc GetRandomNumber(RandomNumberRequest) returns (stream RandomNumberResponse);
  rpc StopRandomNumber(StopRandomNumberRequest) returns (StopRandomNumberResponse);

  rpc GetIncrementalSequence(IncrementalSequenceRequest) returns (stream IncrementalSequenceResponse);
  rpc StopIncrementalSequence(StopIncrementalSequenceRequest) returns (StopIncrementalSequenceResponse);

  rpc Echo(EchoRequest) returns (EchoResponse);
}
