pub const HEARTBEAT_MSG: u16 = 1;

pub const RANDOM_NUMBER_REQUEST: u16 = 2;

pub const STOP_RANDOM_NUMBER_REQUEST: u16 = 3;

pub const INCREMENTAL_SEQUENCE_REQUEST: u16 = 4;

pub const STOP_INCREMENTAL_SEQUENCE_REQUEST: u16 = 5;

pub const ECHO_REQUEST: u16 = 6;

pub const RANDOM_NUMBER_RESPONSE: u16 = 7;

pub const STOP_RANDOM_NUMBER_RESPONSE: u16 = 8;

pub const INCREMENTAL_SEQUENCE_RESPONSE: u16 = 9;

pub const STOP_INCREMENTAL_SEQUENCE_RESPONSE: u16 = 10;

pub const ECHO_RESPONSE: u16 = 11;
